workstation update

diff --git a/dwm/scripts/screen-saver b/dwm/scripts/screen-saver
--- a/dwm/scripts/screen-saver
+++ b/dwm/scripts/screen-saver
@@ -1,49 +1,10 @@
 #!/usr/bin/env bash
 # Dependency checks
-if [ ! $(command -v xrandr) ]; then
-    echo "\"command not found: \"xrandr\"" >&2
+if [ ! $(command -v slock) ]; then
+    echo "\"command not found: \"slock\"" >&2
     exit 1
-fi
-if [ ! $(command -v urxvt) ]; then
-    echo "\"command not found: \"urxvt\"" >&2
-    exit 1
-fi
-if [ ! $(command -v pyxtrlock) ]; then
-    echo "\"command not found: \"pyxtrlock\"" >&2
-    exit 1
-fi
-if [ ! $(command -v asciiquarium) ]; then
-    echo "\"command not found: \"asciiquarium\"" >&2
-    exit 1
-fi
-
-# kill any current instances of screensaver
-pkill -f asciiquarium
-
-# starts screensaver on all monitors
-xrandr --auto
-OFFSETS=(`xrandr -q | grep " connected " | xargs -l | cut -d " " -f1`)
-if [ ${#OFFSETS[@]} -gt 1 ]; then
-    xrandr --output ${OFFSETS[0]} --output ${OFFSETS[1]} --same-as ${OFFSETS[0]}
-else
-    xrandr --output ${OFFSETS[0]} --primary
-fi
-sleep 2 
-urxvt -e sh -c "wmctrl -x -r urxvt -b add,fullscreen; asciiquarium" &
-
-# Store the current layout and set the default one
-if [ $(command -v xkblayout-state) ]; then
-    CURRENT=$(xkblayout-state print %c)
-    xkblayout-state set 0
 fi
 
 # Lock screen, reset monitors and kill screen saver on unlock
 slock 
-pkill -f asciiquarium 
 bash ~/.config/scripts/screen-init 
-
-# Restore kb layout
-if [ $(command -v xkblayout-state) ]; then
-    xkblayout-state set $CURRENT
-fi
-
